# Generated by Django 4.0.1 on 2022-01-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
