# Generated by Django 3.2.9 on 2022-01-29 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_book_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='book',
            name='pdf',
        ),
    ]
