# Generated by Django 3.2.9 on 2022-01-30 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220129_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('notes', 'NOTES'), ('certificate', 'CERTIFICATE'), ('documents', 'DOCUMENTS'), ('question Papers', 'QUESTION PAPERS'), ('study material', 'STUDY MATERIAL')], max_length=50)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='book/cover/')),
            ],
        ),
    ]
